code: 0
swordName: silver sword
swordSpecialSword: 0
swordSpecialPower: 1
candiesNbrOwned: 1002
candiesNbrThrown: 210
candiesNbrEaten: 117
candiesNbrTotal: 6939
candiesCandiesPerSecond: 1
candiesConverterActivated: 0
cauldronBookPage: 0
cauldronCandies: 0
cauldronLollipops: 0
chocolateBarsNbrOwned: 1
farmLollipopsPlanted: 107
farmCurrentFlagIndex: 0
farmPlantingButtonsStep: 2
forgeStep: 0
shopLollipopsButtonsShown: 1
shopShown: 1
shopTicklingStep: 0
shopClickingOnLollipopStep: 0
hutStep: 2
hutSpeech: See by yourself. My prices are high, but the spells are great! (1 klp means 1000 lollipops)
inventoryMagicianHatLetter: 
lollipopsNbrOwned: 7
lollipopsNbrInStock: 111
lollipopsNbrBought: 71
mainNbrOfSecondsSinceLastMinInterval: 23
mainNbrOfSecondsSinceLastHourInterval: 3263
mainNbrOfSecondsSinceLastDayInterval: 3263
mountGoblinBasicChestProbability: 100
peacefulForestBasicChestProbability: 200
peacefulForestPoniesEncountered: 0
objectsHaveObjectKey: 1
objectsHaveObjectHutMap: 1
objectsHaveObjectWellMap: 0
objectsHaveObjectSwampMap: 1
objectsHaveObjectBoots: 1
objectsHaveObjectMagicianHat: 0
objectsHaveObjectPinkRing: 0
objectsHaveObjectForgeMap: 0
objectsHaveObjectCandiesConverter: 0
objectsHaveObjectPlateArmour: 0
objectsHaveObjectCauldron: 0
objectsHaveObjectMagicalHorn: 0
objectsHaveObjectHornOfPlenty: 0
objectsHaveObjectOldAmulet: 0
potionsShownHealth: 0
potionsShownEscape: 0
potionsShownBerserk: 1
potionsShownFireScroll: 0
potionsShownAcidRainScroll: 0
potionsShownTeleportScroll: 0
potionsShownEarthquakeScroll: 0
potionsShownImpInvocationScroll: 0
potionsShownMajorHealth: 0
potionsShownInvulnerability: 0
potionsShownTurtle: 0
potionsShownJelly: 0
potionsShownSeed: 0
potionsShownCloning: 0
potionsShownSuperman: 0
potionsShownGmooh: 0
potionsNbrOwnedHealth: 0
potionsNbrOwnedEscape: 0
potionsNbrOwnedBerserk: 4
potionsNbrOwnedFireScroll: 0
potionsNbrOwnedAcidRainScroll: 0
potionsNbrOwnedTeleportScroll: 0
potionsNbrOwnedEarthquakeScroll: 0
potionsNbrOwnedImpInvocationScroll: 0
potionsNbrOwnedMajorHealth: 0
potionsNbrOwnedInvulnerability: 0
potionsNbrOwnedTurtle: 0
potionsNbrOwnedJelly: 0
potionsNbrOwnedSeed: 0
potionsNbrOwnedCloning: 0
potionsNbrOwnedSuperman: 0
potionsNbrOwnedGmooh: 0
questMaxLandOrder: 2
questTiredTime: 160
spellsFasterCandiesFibo1: 1
spellsFasterCandiesFibo2: 2
swampStep: 17
tabsAnimation: slide
wishingWellSpeech: 
wishingWellStep: 0
yourselfCanSurpass: 0
developperComputerWon: 0